using examenporject_Frameworks_zenodesp.Areas.Identity.Data;
using examenporject_Frameworks_zenodesp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace examenporject_Frameworks_zenodesp.Services
{
	public interface IMyUser
	{
		public EmployeeUser User();
	}

	public class MyUser : IMyUser
	{
		//following code generated by CoPilot, edited in post at public constructor and readonly fields
		private readonly ApplicationDbContext _context;
		private readonly IHttpContextAccessor _httpContextAccessor;
		EmployeeUser user = null;

		public MyUser(ApplicationDbContext dbContext, IHttpContextAccessor httpContext)
		{
			_context = dbContext;
			_httpContextAccessor = httpContext;
		}

		public EmployeeUser User()
		{
			string name = _httpContextAccessor.HttpContext.User.Identity.Name;
			if (user == null || user.UserName != name)
				user = _context.Users.First(u => u.UserName == (string.IsNullOrEmpty(name) ? "dummy" : name));

			return user;
		}
	}
}
